import sanitizeHtml from 'sanitize-html';

export function sanitizePastedHtml(html: string): string {
  return sanitizeHtml(html, {
    allowedTags: [
      'p',
      'br',
      'strong',
      'em',
      'u',
      's',
      'sub',
      'sup',
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'ul',
      'ol',
      'li',
      'blockquote',
      'a',
      'img',
      'code',
      'pre',
      'table',
      'thead',
      'tbody',
      'colgroup',
      'col',
      'tr',
      'th',
      'td',
      'span',
      'mark',
      'hr',
      'div',
      'iframe',
      'audio',
      'source',
      'figure',
      'figcaption',
    ],
    allowedAttributes: {
      a: ['href', 'title', 'target', 'rel'],
      img: ['src', 'alt', 'width', 'height', 'title', 'class'],
      span: ['style'],
      mark: ['style', 'data-color'],
      p: ['style'],
      h1: ['id', 'style'],
      h2: ['id', 'style'],
      h3: ['id', 'style'],
      h4: ['id', 'style'],
      h5: ['id', 'style'],
      h6: ['id', 'style'],
      table: [
        'class',
        'style',
        'data-rw-table-theme',
        'data-rw-table-zebra',
        'data-rw-cell-padding',
        'data-rw-table-float',
      ],
      colgroup: ['span'],
      col: ['style', 'width'],
      tr: ['style'],
      th: ['colspan', 'rowspan', 'style'],
      td: ['colspan', 'rowspan', 'style'],
      div: ['data-page-break', 'class'],
      iframe: ['src', 'title', 'allow', 'allowfullscreen', 'frameborder', 'loading', 'class', 'data-embed'],
      audio: ['src', 'title', 'controls', 'data-embed'],
      source: ['src', 'type'],
      figure: ['class'],
      figcaption: ['class'],
      code: ['class'],
      pre: ['class'],
    },
    allowedStyles: {
      span: {
        color: [/^#(?:[0-9a-fA-F]{3}){1,2}$/],
        'background-color': [/^#(?:[0-9a-fA-F]{3}){1,2}$/],
        'font-size': [/^\d+(?:\.\d+)?(px|rem|em|%)$/],
        'font-family': [/^[^;]+$/],
      },
      mark: {
        'background-color': [/^#(?:[0-9a-fA-F]{3}){1,2}$/],
      },
      p: {
        'text-align': [/^(left|center|right|justify)$/],
        'line-height': [/^\d+(?:\.\d+)?$/],
      },
      h1: {
        'text-align': [/^(left|center|right|justify)$/],
        'line-height': [/^\d+(?:\.\d+)?$/],
      },
      h2: {
        'text-align': [/^(left|center|right|justify)$/],
        'line-height': [/^\d+(?:\.\d+)?$/],
      },
      h3: {
        'text-align': [/^(left|center|right|justify)$/],
        'line-height': [/^\d+(?:\.\d+)?$/],
      },
      h4: {
        'text-align': [/^(left|center|right|justify)$/],
        'line-height': [/^\d+(?:\.\d+)?$/],
      },
      h5: {
        'text-align': [/^(left|center|right|justify)$/],
        'line-height': [/^\d+(?:\.\d+)?$/],
      },
      h6: {
        'text-align': [/^(left|center|right|justify)$/],
        'line-height': [/^\d+(?:\.\d+)?$/],
      },
      table: {
        border: [/^(0|[1-3]px)\s+(solid|dashed|dotted|none)\s+(#(?:[0-9a-fA-F]{3}){1,2}|transparent)$/],
        'border-radius': [/^\d+px$/],
        '--rw-table-border-color': [/^#(?:[0-9a-fA-F]{3}){1,2}$/],
        '--rw-table-radius': [/^\d+px$/],
      },
      col: {
        width: [/^\d+px$/],
      },
      tr: {
        height: [/^\d+px$/],
      },
      th: {
        'text-align': [/^(left|center|right|justify)$/],
        border: [/^(0|[1-3]px)\s+(solid|dashed|dotted|none)\s+(#(?:[0-9a-fA-F]{3}){1,2}|transparent)$/],
        'border-top': [/^(0|[1-3]px)\s+(solid|dashed|dotted|none)\s+(#(?:[0-9a-fA-F]{3}){1,2}|transparent)$/],
        'border-right': [/^(0|[1-3]px)\s+(solid|dashed|dotted|none)\s+(#(?:[0-9a-fA-F]{3}){1,2}|transparent)$/],
        'border-bottom': [/^(0|[1-3]px)\s+(solid|dashed|dotted|none)\s+(#(?:[0-9a-fA-F]{3}){1,2}|transparent)$/],
        'border-left': [/^(0|[1-3]px)\s+(solid|dashed|dotted|none)\s+(#(?:[0-9a-fA-F]{3}){1,2}|transparent)$/],
        'background-color': [/^#(?:[0-9a-fA-F]{3}){1,2}$/],
        color: [/^#(?:[0-9a-fA-F]{3}){1,2}$/],
        'border-radius': [/^\d+px$/],
        padding: [/^\d+px(\s+\d+px){0,3}$/],
      },
      td: {
        'text-align': [/^(left|center|right|justify)$/],
        border: [/^(0|[1-3]px)\s+(solid|dashed|dotted|none)\s+(#(?:[0-9a-fA-F]{3}){1,2}|transparent)$/],
        'border-top': [/^(0|[1-3]px)\s+(solid|dashed|dotted|none)\s+(#(?:[0-9a-fA-F]{3}){1,2}|transparent)$/],
        'border-right': [/^(0|[1-3]px)\s+(solid|dashed|dotted|none)\s+(#(?:[0-9a-fA-F]{3}){1,2}|transparent)$/],
        'border-bottom': [/^(0|[1-3]px)\s+(solid|dashed|dotted|none)\s+(#(?:[0-9a-fA-F]{3}){1,2}|transparent)$/],
        'border-left': [/^(0|[1-3]px)\s+(solid|dashed|dotted|none)\s+(#(?:[0-9a-fA-F]{3}){1,2}|transparent)$/],
        'background-color': [/^#(?:[0-9a-fA-F]{3}){1,2}$/],
        color: [/^#(?:[0-9a-fA-F]{3}){1,2}$/],
        'border-radius': [/^\d+px$/],
        padding: [/^\d+px(\s+\d+px){0,3}$/],
      },
    },
    allowedSchemes: ['http', 'https', 'mailto'],
    allowedIframeHostnames: ['www.youtube.com', 'youtube.com', 'player.vimeo.com'],
    disallowedTagsMode: 'discard',
  });
}
